### ISSUE TITLE
Error copying expect.sh

### ISSUE THREAD

**Issue by Neonica** [babagreensheep/jellyfin-tizen-docker#11]
I've been trying for a while and keep getting this error:
 => ERROR [27/29] COPY --chown=jellyfin ./expect.sh /home/jellyfin/jellyfin-tizen/expect.sh               0.0s
------
 > [27/29] COPY --chown=jellyfin ./expect.sh /home/jellyfin/jellyfin-tizen/expect.sh:
------
failed to compute cache key: "/expect.sh" not found: not found

I've tried downloading the expect.sh directly and tried it in multiple directories but it isn't working still. Do you have an idea of how to fix it? I'm pretty novice at this so it's entirely possible it's on my end but can't work out how to solve it.

**Comment by BlackRapsbeere** [comment]
push. If there is a short line about this problem in the readme - why does nobody seems to care that its is not described well enough?

**Comment by morphygee** [comment]
he has red this line, so he downloaded the file. so have I. 
the problem was solved (for me) when you build the image with this command:
`docker build -f Dockerfile .`
