### ISSUE TITLE
Error building application step 14

### ISSUE THREAD

**Issue by PhilAllmighty** [babagreensheep/jellyfin-tizen-docker#22]
Trying to build on RPI4. Known issue?

 => ERROR [14/28] RUN tizen     certificate         -a Jellyfin         -p 1234         -c SG         -ct  1.4s
------
 > [14/28] RUN tizen     certificate         -a Jellyfin         -p 1234         -c SG         -ct SG         -n Jellyfin         -f Jellyfin:
1.046 /bin/sh: 1: tizen: not found
------
Dockerfile:30
--------------------
  29 |     # Create certificates
  30 | >>> RUN tizen \
  31 | >>>     certificate \
  32 | >>>         -a Jellyfin \
  33 | >>>         -p 1234 \
  34 | >>>         -c SG \
  35 | >>>         -ct SG \
  36 | >>>         -n Jellyfin \  
  37 | >>>         -f Jellyfin
  38 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c tizen     certificate         -a Jellyfin         -p 1234         -c SG         -ct SG         -n Jellyfin         -f Jellyfin" did not complete successfully: exit code: 127

**Comment by RicardoJeronimo** [comment]
I'm getting the exact same error on Arch Linux running Docker 24.0.7. Any fixes?

**Comment by RicardoJeronimo** [comment]
The steps described in [#4 (comment)](https://github.com/babagreensheep/jellyfin-tizen-docker/issues/4#issuecomment-1370297171) didn't work for me, but this did:

1. `sudo systemctl edit docker`:
```
[Service]                                                                                                                     
LimitNOFILE=1048576
```

2. `sudo systemctl edit containerd`:
```
[Service]                                                                                                                     
LimitNOFILE=1048576
```

Credit to: https://bbs.archlinux.org/viewtopic.php?pid=2085385#p2085385

**Comment by PhilAllmighty** [comment]
Thanks! @RicardoJeronimo
