### ISSUE TITLE
java.io.FileNotFoundException: /home/jellyfin/build/.buildResult/config.xml (No such file or directory)

### ISSUE THREAD

**Issue by alexbgameson** [babagreensheep/jellyfin-tizen-docker#33]
Exiting with the following error when running the script:

Using cert/Jellyfin.p12 as Tizen certificate
Building docker image
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  20.99kB
Step 1/42 : FROM node:20 as jellyfin-web
 ---> 21c315c5263c
Step 2/42 : ARG JELLYFIN_BRANCH
 ---> Using cache
 ---> 104bcf9eb224
Step 3/42 : RUN git clone -b ${JELLYFIN_BRANCH} https://github.com/jellyfin/jellyfin-web.git /home/jellyfin/jellyfin-web
 ---> Using cache
 ---> 5d2b15f828a9
Step 4/42 : WORKDIR /home/jellyfin/jellyfin-web
 ---> Using cache
 ---> e3b1b7f6151b
Step 5/42 : RUN SKIP_PREPARE=1 npm ci --no-audit
 ---> Using cache
 ---> 47c82e49427f
Step 6/42 : RUN USE_SYSTEM_FONTS=1 npm run build:production
 ---> Using cache
 ---> 7f5c221850d3
Step 7/42 : FROM node:18 as jellyfin-tizen
 ---> 45f07525ada0
Step 8/42 : RUN useradd -m jellyfin -s /bin/bash
 ---> Using cache
 ---> 1822b8b2ee39
Step 9/42 : USER jellyfin
 ---> Using cache
 ---> 032db4d3e9ca
Step 10/42 : RUN git clone https://github.com/jellyfin/jellyfin-tizen.git /home/jellyfin/jellyfin-tizen
 ---> Using cache
 ---> 4c4a0e1074b0
Step 11/42 : WORKDIR /home/jellyfin/jellyfin-tizen
 ---> Using cache
 ---> f05b76eb53eb
Step 12/42 : COPY --from=jellyfin-web --chown=jellyfin /home/jellyfin/jellyfin-web/dist/ ./dist/
 ---> Using cache
 ---> f1168d6f951a
Step 13/42 : ENV JELLYFIN_WEB_DIR=./dist
 ---> Using cache
 ---> 34e6cdaeab0e
Step 14/42 : RUN npm ci --no-audit
 ---> Using cache
 ---> 2f0023f27f1e
Step 15/42 : FROM ubuntu:22.04 as build
 ---> 8a3cdc4d1ad3
Step 16/42 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 3807a1bbdb65
Step 17/42 : ENV TZ=Poland
 ---> Using cache
 ---> 3cc2b2d3c01f
Step 18/42 : RUN apt-get update && apt-get upgrade -y && apt-get install -y tzdata && apt-get install -y wget git expect
 ---> Using cache
 ---> bd507c445b9e
Step 19/42 : RUN useradd -m jellyfin -s /bin/bash
 ---> Using cache
 ---> 1e426116b8c0
Step 20/42 : USER jellyfin
 ---> Using cache
 ---> e3df65ec01c3
Step 21/42 : RUN wget https://download.tizen.org/sdk/Installer/tizen-studio_5.5/web-cli_Tizen_Studio_5.5_ubuntu-64.bin -P /home/jellyfin
 ---> Using cache
 ---> 7d5bbd36e94e
Step 22/42 : RUN chmod a+x /home/jellyfin/web-cli_Tizen_Studio_5.5_ubuntu-64.bin
 ---> Using cache
 ---> 8a62b1d374bf
Step 23/42 : RUN ./home/jellyfin/web-cli_Tizen_Studio_5.5_ubuntu-64.bin --accept-license /home/jellyfin/tizen-studio
 ---> Using cache
 ---> fbbca68a33df
Step 24/42 : ENV PATH=${PATH}:/home/jellyfin/tizen-studio/tools/ide/bin:/home/jellyfin/tizen-studio/tools
 ---> Using cache
 ---> 1271949a314d
Step 25/42 : WORKDIR /home/jellyfin/build
 ---> Using cache
 ---> 2e4df09436e2
Step 26/42 : COPY --from=jellyfin-tizen --chown=jellyfin /home/jellyfin/jellyfin-tizen/config.xml ./config.xml
 ---> Using cache
 ---> d10e283d7f41
Step 27/42 : COPY --from=jellyfin-tizen --chown=jellyfin /home/jellyfin/jellyfin-tizen/icon.png ./icon.png
 ---> Using cache
 ---> 2b1697621af6
Step 28/42 : COPY --from=jellyfin-tizen --chown=jellyfin /home/jellyfin/jellyfin-tizen/index.html ./index.html
 ---> Using cache
 ---> eb6e37650663
Step 29/42 : COPY --from=jellyfin-tizen --chown=jellyfin /home/jellyfin/jellyfin-tizen/tizen.js ./tizen.js
 ---> Using cache
 ---> c2995a949294
Step 30/42 : COPY --from=jellyfin-tizen --chown=jellyfin /home/jellyfin/jellyfin-tizen/www/ ./www/
 ---> Using cache
 ---> c7f55c19f7d3
Step 31/42 : ARG CERT_PASSWORD
 ---> Using cache
 ---> b50bb8cef580
Step 32/42 : ARG CERT_FILENAME
 ---> Using cache
 ---> f04f8b682208
Step 33/42 : ARG CERT_NAME
 ---> Using cache
 ---> 8cb3d5dbb51d
Step 34/42 : COPY cert/${CERT_FILENAME}.p12 /home/jellyfin/tizen-studio-data/keystore/author/Jellyfin.p12
 ---> Using cache
 ---> 1ae0c333c2d6
Step 35/42 : RUN tizen security-profiles add -n ${CERT_NAME} -a /home/jellyfin/tizen-studio-data/keystore/author/Jellyfin.p12 -p ${CERT_PASSWORD}
 ---> Using cache
 ---> c1c373139fe6
Step 36/42 : RUN sed -i 's/\/home\/jellyfin\/tizen-studio-data\/keystore\/author\/Jellyfin.pwd//' /home/jellyfin/tizen-studio-data/profile/profiles.xml
 ---> Using cache
 ---> fbe5a8392e8b
Step 37/42 : RUN sed -i 's/\/home\/jellyfin\/tizen-studio-data\/tools\/certificate-generator\/certificates\/distributor\/tizen-distributor-signer.pwd/tizenpkcs12passfordsigner/' /home/jellyfin/tizen-studio-data/profile/profiles.xml
 ---> Using cache
 ---> 92a5c066ebf5
Step 38/42 : RUN tizen build-web
 ---> Running in 27a24539e63e
Build Web Application:   80% ( 8/10)Error occurred during build!
        java.io.FileNotFoundException: /home/jellyfin/build/.buildResult/config.xml (No such file or directory)
Total time: 00:00:00.524
The command '/bin/sh -c tizen build-web' returned a non-zero code: 1

**Comment by alexbgameson** [comment]
Worked on different machine.

**Comment by knowsshit** [comment]
Same issue on both my mine (running Fedora 40). Not sure what to do about this.

**Comment by solarchemist** [comment]
I experienced exactly this issue after installing `apt install docker docker.io` on Ubuntu 22.04.

I think the cause might be an "improper" Docker installation. After adding the Docker repo to `/etc/apt/sources.list.d/docker.list`  and installing `apt install docker-ce` (following [this DigitalOcean guide](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-22-04)) this repo then executed flawlessly (and with quite different output compared to before) and Jellyfin works great on the TV :-) 
Big, big thumbs up to @babagreensheep and all the contributors!

**Comment by Temporalin** [comment]
Just happened to me using Docker version 27.3.1, build ce1223035 in Arch Linux. This other project worked for me https://github.com/Georift/install-jellyfin-tizen , so I think something may be outdated here
