### ISSUE TITLE
Stuck at step 24

### ISSUE THREAD

**Issue by xploz1on** [babagreensheep/jellyfin-tizen-docker#5]
Hi there. I been trying to do everything but for some reason after reaching step 24 it stays there forever. Let it run for 4 hours and nothing. Repeated everything and the same happened.

```
# Build apps
WORKDIR /home/jellyfin/jellyfin-web
RUN npm ci --no-audit
WORKDIR /home/jellyfin/jellyfin-tizen
ENV JELLYFIN_WEB_DIR=/home/jellyfin/jellyfin-web/dist
RUN npm ci --no-audit
```

Wiped all images and started again...

**Comment by xploz1on** [comment]
Managed to build the app. Third time was the one!
 Tv in developer mode but wont show on the container. I'll see what i can do
 
 EDIT: All good!

**Comment by squealteam6** [comment]
how did you solve this issue?

**Comment by Deiiv** [comment]
@squealteam6 I was just about to reply but it got past, so it just takes time it seems. Either wait it out or retry the build (mine took roughly 20-30 minutes I think, even though it finished installing the packages within 2 minutes)
