### ISSUE TITLE
Author certificate mismatch

### ISSUE THREAD

**Issue by gogo199432** [babagreensheep/jellyfin-tizen-docker#6]
Might be just me, but I tried to do this today, and I get all the way to tizen install, but then it fails with "Author certificate mismatch"
Log:
```
Transferring the package...
Transferred the package: /home/jellyfin/jellyfin-tizen/Jellyfin.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install AprZAARz4r.Jellyfin
package_path /home/owner/share/tmp/sdk_tools/tmp/Jellyfin.wgt
app_id[AprZAARz4r.Jellyfin] install start
app_id[AprZAARz4r.Jellyfin] installing[8]
app_id[AprZAARz4r.Jellyfin] installing[11]
app_id[AprZAARz4r.Jellyfin] installing[13]
app_id[AprZAARz4r.Jellyfin] installing[15]
app_id[AprZAARz4r.Jellyfin] installing[17]
app_id[AprZAARz4r.Jellyfin] installing[20]
app_id[AprZAARz4r.Jellyfin] installing[22]
app_id[AprZAARz4r.Jellyfin] installing[24]
app_id[AprZAARz4r.Jellyfin] installing[26]
app_id[AprZAARz4r.Jellyfin] installing[28]
app_id[AprZAARz4r.Jellyfin] installing[31]
app_id[AprZAARz4r.Jellyfin] installing[33]
app_id[AprZAARz4r.Jellyfin] install failed[118, -11], reason: Author certificate not match :
spend time for wascmd is [6189]ms
Failed to install Tizen application.
Total time: 00:00:09.533
```

**Comment by ryangreenj** [comment]
I am getting a similar but slightly different error on this step as well. Any luck with a fix?

```Transferring the package...
Transferred the package: /home/jellyfin/jellyfin-tizen/Jellyfin.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install AprZAARz4r.Jellyfin
package_path /home/owner/share/tmp/sdk_tools/tmp/Jellyfin.wgt
was_install_app return WAS_TRUE
app_id[AprZAARz4r.Jellyfin] install start
app_id[AprZAARz4r.Jellyfin] installing[10]
app_id[AprZAARz4r.Jellyfin] installing[12]
app_id[AprZAARz4r.Jellyfin] installing[15]
app_id[AprZAARz4r.Jellyfin] installing[17]
app_id[AprZAARz4r.Jellyfin] installing[20]
app_id[AprZAARz4r.Jellyfin] installing[22]
app_id[AprZAARz4r.Jellyfin] installing[25]
app_id[AprZAARz4r.Jellyfin] install failed[118, -12], reason: Check certificate error : :Invalid signature. Signed with wrong key, changed signature file or changed package file.:<-4>
spend time for wascmd is [16591]ms
cmd_ret:0
Failed to install Tizen application.
Total time: 00:00:17.959```

**Comment by babagreensheep** [comment]
Seems like a Tizen cert issue. I'll investigate and update.

**Comment by louregni** [comment]
In my case, during an attempt to upgrade an existing version of Jellyfin on my TV.
The update failed with the same error.
Since I generated two certificates, one each installation, it seems that you cannot upgrade with a build signed with a different certificate of the installed build.
So you have to uninstall the app on the TV. And install a fresh one with the "latest" certificate generated.

**Comment by keteflips** [comment]
Another similar error here:

 => ERROR [22/29] RUN npm ci --no-audit                                                                           31.4s
------
 > [22/29] RUN npm ci --no-audit:
#25 6.864 npm ERR! Error while executing:
#25 6.864 npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/ThaUnknown/event-target-polyfill.git
#25 6.864 npm ERR!
#25 6.864 npm ERR! Host key verification failed.
#25 6.864 npm ERR! fatal: Could not read from remote repository.
#25 6.864 npm ERR!
#25 6.865 npm ERR! Please make sure you have the correct access rights
#25 6.865 npm ERR! and the repository exists.
#25 6.865 npm ERR!
#25 6.865 npm ERR! exited with error code: 128
#25 29.74
#25 29.74 npm ERR! A complete log of this run can be found in:
#25 29.74 npm ERR!     /home/jellyfin/.npm/_logs/2023-04-19T07_03_31_570Z-debug.log
------
executor failed running [/bin/sh -c npm ci --no-audit]: exit code: 1

**Comment by skewll** [comment]
> 

I have the same issue. Can you open this as an issue so perhaps it can get some attention?

**Comment by ld9** [comment]
> Another similar error here:
> ## => ERROR [22/29] RUN npm ci --no-audit 31.4s
> 
> > [22/29] RUN npm ci --no-audit:
> > #25 6.864 npm ERR! Error while executing:
> > #25 6.864 npm ERR! /usr/bin/git ls-remote -h -t ssh://[git@github.com](mailto:git@github.com)/ThaUnknown/event-target-polyfill.git
> > #25 6.864 npm ERR!
> > #25 6.864 npm ERR! Host key verification failed.
> > #25 6.864 npm ERR! fatal: Could not read from remote repository.
> > #25 6.864 npm ERR!
> > #25 6.865 npm ERR! Please make sure you have the correct access rights
> > #25 6.865 npm ERR! and the repository exists.
> > #25 6.865 npm ERR!
> > #25 6.865 npm ERR! exited with error code: 128
> > #25 29.74
> > #25 29.74 npm ERR! A complete log of this run can be found in:
> > #25 29.74 npm ERR!     /home/jellyfin/.npm/_logs/2023-04-19T07_03_31_570Z-debug.log
> 
> executor failed running [/bin/sh -c npm ci --no-audit]: exit code: 1

Although I don't know if I'd call this a clean fix, the issue seems to be different, and can be worked around by adding `RUN git config --global url.https://github.com/.insteadOf ssh://git@github.com/` as a step prior to running `npm ci --no-audit`.

**Comment by skewll** [comment]
Thank you!

**Comment by skewll** [comment]
> Another similar error here:
> 
> ## => ERROR [22/29] RUN npm ci --no-audit 31.4s
> > [22/29] RUN npm ci --no-audit:
> > #25 6.864 npm ERR! Error while executing:
> > #25 6.864 npm ERR! /usr/bin/git ls-remote -h -t ssh://[git@github.com](mailto:git@github.com)/ThaUnknown/event-target-polyfill.git
> > #25 6.864 npm ERR!
> > #25 6.864 npm ERR! Host key verification failed.
> > #25 6.864 npm ERR! fatal: Could not read from remote repository.
> > #25 6.864 npm ERR!
> > #25 6.865 npm ERR! Please make sure you have the correct access rights
> > #25 6.865 npm ERR! and the repository exists.
> > #25 6.865 npm ERR!
> > #25 6.865 npm ERR! exited with error code: 128
> > #25 29.74
> > #25 29.74 npm ERR! A complete log of this run can be found in:
> > #25 29.74 npm ERR!     /home/jellyfin/.npm/_logs/2023-04-19T07_03_31_570Z-debug.log
> 
> executor failed running [/bin/sh -c npm ci --no-audit]: exit code: 1

Even after getting past this step, I get so many errors that at this point I don't believe any of the guides are currently up to date and working.

**Comment by ld9** [comment]
@skewll 

It seems that the PR https://github.com/babagreensheep/jellyfin-tizen-docker/pull/13 fixes the current issue. I tried this fix yesterday evening and was able to successfully build. AFAIK It's unrelated to the original certificate issue this thread started with. If the fix from that branch doesn't work, it may be best to open a new issue specifically for this. 

Someone can correct me if I'm wrong.

**Comment by skewll** [comment]
I actually tried a few days ago to upgrade node and npm but ran into more
errors.  I'll give it another go today.

**Comment by skewll** [comment]
> @skewll
> 
> It seems that the PR #13 fixes the current issue. I tried this fix yesterday evening and was able to successfully build. AFAIK It's unrelated to the original certificate issue this thread started with. If the fix from that branch doesn't work, it may be best to open a new issue specifically for this.
> 
> Someone can correct me if I'm wrong.

The only changes that are needed to the Dockerfile are:

change the node version to 18x
remove the npm update line all together.

**Comment by Ranbato** [comment]
Add the following command before installing
`tizen uninstall -p AprZAARz4r.Jellyfin -t <DEVICE_ID>`
