### ISSUE TITLE
Problem connecting to TV

### ISSUE THREAD

**Issue by EinMaulwurf** [babagreensheep/jellyfin-tizen-docker#8]
Hello,
as a preface: I'm a noob and setting up Jellyfin on a ubuntu server is the first time doing something like this for me. So maybe I'm just stupid.

I enabled developer mode on my TV and gave it the IP adress of my server. I also built the application and ran `docker run -it --rm jellyfin` followed by `jellyfin@26704353ef4c:~/jellyfin-tizen$ sdb connect 192.168.188.45`. I'm pretty shure that this is the right IP adress, I got it by looking under the network section of my router.
The output then was
`* Server is not running. Start it now on port 26099 *`
`* Server has started successfully *`
`connecting to 192.168.188.45:26101 ...`
`failed to connect to 192.168.188.45:26101`

At this point I don't know what to do.

I did not install Tizen Studio or anything else, do I need to this that?

**Comment by kartikynwa** [comment]
Can you try this `docker run` command instead?

```
docker run -it --rm --network host jellyfin
```

**Comment by EinMaulwurf** [comment]
Still no luck:
```
einmaulwurf@titanic:~/docker-projects/jellyfin-tizen$ sudo docker run -it --rm --network host jellyfin
jellyfin@titanic:~/jellyfin-tizen$ sdb connect 192.168.188.45
* Server is not running. Start it now on port 26099 *
* Server has started successfully *
connecting to 192.168.188.45:26101 ...
failed to connect to 192.168.188.45:26101
jellyfin@titanic:~/jellyfin-tizen$ 
```

**Comment by EinMaulwurf** [comment]
I was able to get it running by resetting the TV to factory settings.
